name: docs

on:
  push:
    branches: 
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: true

      - run: git clone --recursive https://github.com/AI4EPS/QuakeFlow.git docs/lectures/codes/QuakeFlow/

      # - name: Convert Markdown into HTML and PDF
      #   uses: KoharaKazuya/marp-cli-action@v2
      #   with:
      #     config-file: .marprc.yml
      
      - uses: actions/setup-node@v3
      - run: npx @marp-team/marp-cli@latest docs/lectures

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-jupyter mkdocs-autorefs mkdocs-bibtex mkdocs-redirects
      - run: mkdocs gh-deploy --force

      # - uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     python-version: 3.8
      #     miniconda-version: "latest"
      #     activate-environment: mkdocs
      #     environment-file: .github/environment.yml

      # - name: mkdocs
      #   shell: bash -el {0}
      #   run: |
      #     pip install mkdocs-autorefs mkdocs-monorepo-plugin mkdocs-bibtex mkdocs-redirects
      #     mkdocs gh-deploy --force


